openapi: "3.0.3"
info:
  title: AI Todo Chatbot API
  version: "1.0.0"
  description: Chat endpoint for natural language todo management

paths:
  /api/chat:
    post:
      summary: Send a message to the AI chatbot
      description: |
        Accepts a natural language message, runs the AI agent with
        MCP tools, and returns the assistant's response. User identity
        is resolved from the JWT Bearer token (never from request body
        or URL parameters).
      operationId: chatWithAgent
      tags: [chat]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
      responses:
        "200":
          description: Successful chat response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatResponse"
        "401":
          description: Authentication required or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Agent execution or AI provider failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/chat/history:
    get:
      summary: Get conversation history
      description: |
        Returns the user's conversation messages ordered by creation
        time. Creates a new conversation if none exists. User identity
        resolved from JWT.
      operationId: getChatHistory
      tags: [chat]
      security:
        - BearerAuth: []
      parameters:
        - name: conversation_id
          in: query
          required: false
          schema:
            type: string
          description: Specific conversation ID (uses latest if omitted)
      responses:
        "200":
          description: Conversation history
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatHistoryResponse"
        "401":
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required: [message]
      properties:
        conversation_id:
          type: string
          nullable: true
          description: Existing conversation ID (creates new if omitted)
        message:
          type: string
          minLength: 1
          description: User's natural language message

    ChatResponse:
      type: object
      required: [conversation_id, response, tool_calls]
      properties:
        conversation_id:
          type: string
          description: The conversation ID
        response:
          type: string
          description: AI assistant's response text
        tool_calls:
          type: array
          items:
            $ref: "#/components/schemas/ToolCall"
          description: MCP tools invoked during this turn

    ToolCall:
      type: object
      properties:
        tool_name:
          type: string
        arguments:
          type: object
        result:
          type: object

    ChatHistoryResponse:
      type: object
      required: [conversation_id, messages]
      properties:
        conversation_id:
          type: string
        messages:
          type: array
          items:
            $ref: "#/components/schemas/ChatMessage"

    ChatMessage:
      type: object
      required: [id, role, content, created_at]
      properties:
        id:
          type: string
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
        created_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required: [error, message, timestamp]
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
