openapi: 3.1.0
info:
  title: Todo API - Enhanced Endpoints
  description: Extended todo endpoints with due dates, priorities, tags, and filtering
  version: 2.0.0

servers:
  - url: http://localhost:8000
    description: Local development

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Better Auth JWT token

  schemas:
    Priority:
      type: string
      enum: [high, medium, low]
      description: Task priority level

    TagSummary:
      type: object
      properties:
        id:
          type: string
          maxLength: 21
        name:
          type: string
          maxLength: 50
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
      required: [id, name, color]

    TodoResponse:
      type: object
      properties:
        id:
          type: string
          maxLength: 21
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        completed:
          type: boolean
        user_id:
          type: string
          maxLength: 36
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        due_date:
          type: string
          format: date
          nullable: true
          description: Due date (YYYY-MM-DD format)
        priority:
          $ref: '#/components/schemas/Priority'
          nullable: true
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagSummary'
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at
        - tags

    TodoCreate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          nullable: true
        due_date:
          type: string
          format: date
          nullable: true
        priority:
          $ref: '#/components/schemas/Priority'
          nullable: true
        tag_ids:
          type: array
          items:
            type: string
            maxLength: 21
          description: Array of tag IDs to assign
      required: [title]

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          nullable: true
        completed:
          type: boolean
        due_date:
          type: string
          format: date
          nullable: true
        priority:
          $ref: '#/components/schemas/Priority'
          nullable: true
        tag_ids:
          type: array
          items:
            type: string
            maxLength: 21
          description: Array of tag IDs (replaces existing tags)

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string
        timestamp:
          type: string
          format: date-time
      required: [detail]

paths:
  /todos:
    get:
      operationId: listTodos
      summary: List todos with filtering and sorting
      description: |
        Returns all todos for the authenticated user.
        Supports filtering by search term, priority, tags, due date range, and completion status.
        Supports sorting by created_at, due_date, or priority.
      parameters:
        - name: search
          in: query
          description: Case-insensitive search in title and description
          schema:
            type: string
        - name: priority
          in: query
          description: Filter by priority levels (repeatable for multiple)
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Priority'
          style: form
          explode: true
        - name: tag
          in: query
          description: Filter by tag IDs (repeatable for multiple, OR logic)
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: due_before
          in: query
          description: Filter todos due on or before this date
          schema:
            type: string
            format: date
        - name: due_after
          in: query
          description: Filter todos due on or after this date
          schema:
            type: string
            format: date
        - name: status
          in: query
          description: Filter by completion status
          schema:
            type: string
            enum: [all, active, completed]
            default: all
        - name: sort
          in: query
          description: Sort order
          schema:
            type: string
            enum: [created_at, due_date, priority]
            default: created_at
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      operationId: createTodo
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: Todo created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
        '401':
          description: Unauthorized
        '422':
          description: Validation error

  /todos/{todo_id}:
    parameters:
      - name: todo_id
        in: path
        required: true
        schema:
          type: string
          maxLength: 21

    get:
      operationId: getTodo
      summary: Get a specific todo
      responses:
        '200':
          description: Todo details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
        '401':
          description: Unauthorized
        '404':
          description: Todo not found

    patch:
      operationId: updateTodo
      summary: Update a todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
        '401':
          description: Unauthorized
        '404':
          description: Todo not found
        '422':
          description: Validation error

    delete:
      operationId: deleteTodo
      summary: Delete a todo
      responses:
        '204':
          description: Todo deleted
        '401':
          description: Unauthorized
        '404':
          description: Todo not found
